# main = ".open-next/worker.js"
name = "connections"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
# assets = { directory = ".open-next/assets", binding = "ASSETS" }